name: Build and Deploy

on:
  push:
    branches:
      - production
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    node-versions: node 18

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun build

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       if: github.event_name == 'push' && github.ref == 'refs/heads/production' && contains(github.event.head_commit.message, 'deploy')
  #       run: bun deploy github-pages  # Use Bun to deploy to GitHub Pages

  #     - name: Deploy to Netlify
  #       if: github.event_name == 'push' && github.ref == 'refs/heads/production' && contains(github.event.head_commit.message, 'deploy')
  #       run: bun deploy netlify  # Use Bun to deploy to Netlify
