name: Build and Deploy

on:
  push:
    branches:
      - production
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       on:
  #         push:
  #           branches: production
            # if: github.event_name == 'push' && github.ref == 'refs/heads/production' && contains(github.event.head_commit.message, 'deploy')
              # run: bun run deploy

      # - name: Deploy to Netlify
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/production' && contains(github.event.head_commit.message, 'deploy')
      #   run: bun deploy netlify
